nixiesearch/nixiesearch

README.md
Hopefully we won't be murdered by the army of vector search engine builders.
=> add snippet for not-vector-engine in the readme

.github/workflows/deploy-site.yml, .github/workflows/docs-ci.yml
So noone will be able to commit broken docs.
=> add ci for mkdocs

src/main/scala/ai/nixiesearch/main/CliConfig.scala
as scallop does exactly that, breaking all my precious async setup with monads
=> do not do system.exit on cli parsing failure

deploy/nixiesearch.sh
Should increase the performance on JVM19+
=> add jvm vector incubator module flag

docs/docs/concepts/index.md, docs/docs/reference/api/index/document-format.md, docs/docs/reference/api/index/field-types.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/core/Document.scala, src/test/scala/ai/nixiesearch/core/DocumentJsonTest.scala
=> Support nested docs

.github/workflows/tests.yml
=> use jdk20 for CI runs

build.sbt, docs/docs/reference/api/search/filter.md, src/main/scala/ai/nixiesearch/api/aggregation/Aggregation.scala, src/main/scala/ai/nixiesearch/api/filter/Predicate.scala, src/main/scala/ai/nixiesearch/core/FiniteRange.scala, src/test/scala/ai/nixiesearch/api/query/aggregation/RangeAggregationTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/BoolFilterTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/RangeFilterTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/json/FilterJsonTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/json/RangeJsonTest.scala
next step - do the same for facets
=> Support gt/gte/lt/lte in range filters

docs/docs/reference/api/search/facet.md, src/main/scala/ai/nixiesearch/api/aggregation/Aggregation.scala, src/main/scala/ai/nixiesearch/core/aggregate/TermAggregator.scala, src/test/scala/ai/nixiesearch/api/query/aggregation/json/TermAggregationJsonTest.scala
=> add 'all' as a valid term agg size parameter

build.sbt, build_docker.sh
=> support arm64 docker image

docs/docs/reference/api/suggest.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/api/SuggestRoute.scala, src/main/scala/ai/nixiesearch/core/search/Suggester.scala, src/test/scala/ai/nixiesearch/api/SuggestRouteTest.scala, src/test/scala/ai/nixiesearch/api/query/json/SuggestQueryJsonTest.scala
=> add docs for suggestions

build.sbt, docs/docs/reference/config/cache.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/api/SuggestRoute.scala, src/main/scala/ai/nixiesearch/config/CacheConfig.scala, src/main/scala/ai/nixiesearch/config/Config.scala, src/main/scala/ai/nixiesearch/config/CoreConfig.scala, src/main/scala/ai/nixiesearch/config/mapping/FieldSchema.scala, src/main/scala/ai/nixiesearch/config/mapping/IndexMapping.scala, src/main/scala/ai/nixiesearch/core/nn/model/BiEncoderCache.scala, src/main/scala/ai/nixiesearch/core/nn/model/OnnxBiEncoder.scala, src/main/scala/ai/nixiesearch/core/nn/model/OnnxSession.scala, src/main/scala/ai/nixiesearch/core/search/lucene/SemanticLuceneQuery.scala, src/main/scala/ai/nixiesearch/index/IndexRegistry.scala, src/main/scala/ai/nixiesearch/index/IndexWriter.scala, src/main/scala/ai/nixiesearch/main/Standalone.scala, src/test/scala/ai/nixiesearch/core/nn/model/OnnxBiEncoderTest.scala, src/test/scala/ai/nixiesearch/util/LocalIndexFixture.scala, src/test/scala/ai/nixiesearch/util/SearchTest.scala, src/test/scala/ai/nixiesearch/util/TestIndexRegistry.scala
=> add embed cache

src/main/scala/ai/nixiesearch/core/nn/model/HuggingFaceClient.scala
As otherwise it always sends a request to HF slowing down tests.
=> add caching for HF responses

src/main/scala/ai/nixiesearch/api/SearchRoute.scala, src/main/scala/ai/nixiesearch/core/search/Searcher.scala
Aligns the implementation with the documentation. Unfortunately locally 'sbt test' runs into OOM issues, so I cannot fully verify the change.
=> Rename filter -> filters in REST handler

src/main/scala/ai/nixiesearch/config/Config.scala, src/test/resources/config/config.yml, src/test/scala/ai/nixiesearch/config/ConfigTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/196
=> add check that config file has at least one index defined

build.sbt, docs/docs/reference/config/url.md, project/Deps.scala, src/main/scala/ai/nixiesearch/util/source/URLReader.scala, src/test/scala/ai/nixiesearch/util/source/URLReaderTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/191
=> Support file decompression

src/main/scala/ai/nixiesearch/main/CliConfig.scala, src/main/scala/ai/nixiesearch/main/Main.scala, src/main/scala/ai/nixiesearch/main/args/ArgConverter.scala, src/main/scala/ai/nixiesearch/main/args/FileConverter.scala, src/main/scala/ai/nixiesearch/main/args/HostnameConverter.scala, src/main/scala/ai/nixiesearch/main/args/LoglevelConverter.scala, src/main/scala/ai/nixiesearch/main/args/PortConverter.scala, src/main/scala/ai/nixiesearch/main/args/URLConverter.scala, src/main/scala/ai/nixiesearch/main/args/package.scala, src/test/scala/ai/nixiesearch/main/CliConfigTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/192
=> add cli arg to override log level

src/main/scala/ai/nixiesearch/api/SearchRoute.scala, src/main/scala/ai/nixiesearch/util/source/URLReader.scala, src/test/scala/ai/nixiesearch/util/source/URLReaderTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/200
=> fix flaky URLReaderTest test

docs/docs/concepts/autocomplete.md, docs/docs/reference/api/suggest.md, src/main/scala/ai/nixiesearch/api/IndexRoute.scala, src/main/scala/ai/nixiesearch/api/SearchRoute.scala, src/main/scala/ai/nixiesearch/core/suggest/GeneratedSuggestions.scala, src/main/scala/ai/nixiesearch/core/suggest/SuggestionRanker.scala, src/main/scala/ai/nixiesearch/core/suggest/rank/DeduplicateProcessor.scala, src/main/scala/ai/nixiesearch/core/suggest/rank/LTRSuggestionProcessor.scala, src/main/scala/ai/nixiesearch/core/suggest/rank/RRFSuggestionProcessor.scala, src/main/scala/ai/nixiesearch/core/suggest/rank/SuggestionProcessor.scala, src/main/scala/ai/nixiesearch/index/Searcher.scala, src/test/resources/datasets/movies/config.yaml, src/test/resources/datasets/movies/movies.jsonl, src/test/resources/datasets/movies/movies.jsonl.gz, src/test/scala/ai/nixiesearch/api/suggest/SuggestSingleFieldTest.scala, src/test/scala/ai/nixiesearch/e2e/MSMarcoEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/MoviesSuggestionEndToEndTest.scala, src/test/scala/ai/nixiesearch/main/subcommands/IndexModeTest.scala, src/test/scala/ai/nixiesearch/util/DatasetLoader.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/172
=> RRF for suggestion ranking

src/main/scala/ai/nixiesearch/main/CliConfig.scala, src/main/scala/ai/nixiesearch/util/Version.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/208
=> fix hang on incorrect cmdline options

docs/docs/reference/cli/index.md
Document requirement to flush the index after indexing documents.
=> Document flush endpoint

docs/docs/reference/api/admin/list-indices.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/api/AdminRoute.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/176
=> API: _indexes call

docs/docs/index.md, docs/docs/reference/api/index/field-types.md, docs/docs/reference/api/search/facet.md, docs/docs/reference/api/search/filter.md, docs/docs/reference/config/mapping.md, src/main/scala/ai/nixiesearch/api/filter/Predicate.scala, src/main/scala/ai/nixiesearch/config/mapping/FieldSchema.scala, src/main/scala/ai/nixiesearch/config/mapping/IndexMapping.scala, src/main/scala/ai/nixiesearch/core/Document.scala, src/main/scala/ai/nixiesearch/core/Field.scala, src/main/scala/ai/nixiesearch/core/codec/BooleanFieldWriter.scala, src/main/scala/ai/nixiesearch/core/codec/DoubleFieldWriter.scala, src/main/scala/ai/nixiesearch/index/Indexer.scala, src/test/scala/ai/nixiesearch/api/query/filter/BoolTermFilterTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/NumTermFilterTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/StringTermFilterTest.scala, src/test/scala/ai/nixiesearch/api/query/filter/json/TermJsonTest.scala, src/test/scala/ai/nixiesearch/core/DocumentJsonTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/228
=> boolean field support

src/main/scala/ai/nixiesearch/api/IndexRoute.scala, src/main/scala/ai/nixiesearch/core/PrintProgress.scala, src/main/scala/ai/nixiesearch/main/subcommands/IndexMode.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/194
=> print indexing progress for standalone/index modes

src/main/scala/ai/nixiesearch/config/mapping/DurationJson.scala, src/main/scala/ai/nixiesearch/config/mapping/IndexConfig.scala, src/main/scala/ai/nixiesearch/main/subcommands/IndexMode.scala, src/main/scala/ai/nixiesearch/main/subcommands/StandaloneMode.scala, src/main/scala/ai/nixiesearch/main/subcommands/util/PeriodicFlushStream.scala
And also fix broken auto flush on standalone mode. Fixes https://github.com/nixiesearch/nixiesearch/issues/227
=> expose index flush interval in config

src/main/scala/ai/nixiesearch/core/Document.scala, src/main/scala/ai/nixiesearch/core/Field.scala, src/main/scala/ai/nixiesearch/index/Indexer.scala, src/main/scala/ai/nixiesearch/index/sync/LocalIndex.scala, src/main/scala/ai/nixiesearch/index/sync/MasterIndex.scala, src/main/scala/ai/nixiesearch/index/sync/ReplicatedIndex.scala, src/test/scala/ai/nixiesearch/core/DocumentJsonTest.scala
Otherwise it was using FloatField for all numbers, and it clashed with int/long/double field types in mapping.
=> cast json number types according to mapping

docs/docs/reference/api/admin/stats.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/api/StatsRoute.scala, src/main/scala/ai/nixiesearch/index/IndexStats.scala, src/main/scala/ai/nixiesearch/main/subcommands/SearchMode.scala, src/main/scala/ai/nixiesearch/main/subcommands/StandaloneMode.scala, src/test/scala/ai/nixiesearch/api/StatsRouteTest.scala, src/test/scala/ai/nixiesearch/index/IndexStatsTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/224
=> index stats api

docs/docs/reference/cli/standalone.md, src/main/scala/ai/nixiesearch/config/Config.scala, src/main/scala/ai/nixiesearch/main/CliConfig.scala, src/test/scala/ai/nixiesearch/main/CliConfigTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/171
=> remote config loading support

build_docker.sh, src/main/scala/ai/nixiesearch/api/API.scala, src/test/scala/ai/nixiesearch/api/CORSTest.scala
=> API: add CORS allow all header

project/Deps.scala, src/main/scala/ai/nixiesearch/core/codec/NixiesearchCodec.scala, src/test/scala/ai/nixiesearch/index/IndexStatsTest.scala
Technically it's a breaking change, as index format is going to change.
=> Bump lucene to 9.12

README.md, build_readme.sh
Fixes https://github.com/nixiesearch/nixiesearch/issues/331
=> fix broken links in github readme

.github/workflows/tests.yml, build.sbt, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModel.scala, src/test/scala/ai/nixiesearch/core/nn/model/embedding/OnnxBiEncoderTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/365
=> fix support for XLM based models

src/main/scala/ai/nixiesearch/core/nn/model/ModelFileCache.scala
fixes: https://github.com/nixiesearch/nixiesearch/issues/364
Now the cache saving is atomic: happens only on successful model download.
=> make model file cache atomic

src/main/scala/ai/nixiesearch/api/IndexRoute.scala, src/main/scala/ai/nixiesearch/api/MappingRoute.scala, src/main/scala/ai/nixiesearch/api/Route.scala, src/main/scala/ai/nixiesearch/api/SearchRoute.scala, src/main/scala/ai/nixiesearch/api/StatsRoute.scala, src/main/scala/ai/nixiesearch/config/mapping/IndexMapping.scala, src/test/scala/ai/nixiesearch/api/SearchRouteTest.scala
fixes #272 
now all routes correctly handle aliased paths
=> fix alias support

src/main/scala/ai/nixiesearch/api/IndexRoute.scala, src/main/scala/ai/nixiesearch/index/Indexer.scala, src/main/scala/ai/nixiesearch/index/Searcher.scala, src/test/scala/ai/nixiesearch/api/query/UpdateDeleteTest.scala
So technically it was not exposed in the REST API.
=> unbreak document deletes

.github/workflows/tests.yml
=> add nixie cache dirs to ci cache

docs/docs/reference/config.md, src/main/scala/ai/nixiesearch/config/Config.scala, src/main/scala/ai/nixiesearch/config/CoreConfig.scala, src/main/scala/ai/nixiesearch/config/SearcherConfig.scala, src/main/scala/ai/nixiesearch/main/CliConfig.scala, src/main/scala/ai/nixiesearch/main/Main.scala, src/main/scala/ai/nixiesearch/main/subcommands/SearchMode.scala, src/main/scala/ai/nixiesearch/main/subcommands/StandaloneMode.scala, src/test/scala/ai/nixiesearch/config/ConfigEnvSubstTest.scala, src/test/scala/ai/nixiesearch/config/ConfigTest.scala, src/test/scala/ai/nixiesearch/e2e/MSMarcoEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/MoviesSuggestionEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/RAGEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/RemoteIndexSearchEndToEndTest.scala
so you can set NIXIESEARCH_* and override config vars.
=> add env override support

src/main/scala/ai/nixiesearch/core/nn/model/generative/GenerativeModel.scala, src/test/resources/datasets/movies/config-rag.yaml
To make CI more deterministic.
=> pass --seed option to llamacpp-server

src/main/scala/ai/nixiesearch/core/nn/model/generative/GenerativeModel.scala
Trace:
```
17:51:53.251 WARN  o.h.ember.client.EmberClientBuilder - timeout (120 seconds) is >= idleConnectionTime (60 seconds). It is recommended to configure timeout < idleConnectionTime, or disable one of them explicitly by setting it to Duration.Inf.
17:51:53.253 INFO  a.n.core.nn.model.HuggingFaceClient - found cached model_card.json card
17:51:53.253 INFO  a.n.c.n.m.g.GenerativeModelDict$ - Fetching hf://bartowski/gemma-2-27b-it-GGUF from HF: model=gemma-2-27b-it-Q4_K_L.gguf
17:51:53.253 INFO  a.n.core.nn.model.HuggingFaceClient - found cached /cache/models/bartowski/gemma-2-27b-it-GGUF/gemma-2-27b-it-Q4_K_L.gguf file for requested bartowski/gemma-2-27b-it-GGUF/gemma-2-27b-it-Q4_K_L.gguf
17:51:53.260 INFO  a.n.llamacppserver.LlamacppServer - Unpacking llamacpp-server for os=linux …
```
=> fix crash in readiness probe when llamacpp takes some time to spin up

src/main/scala/ai/nixiesearch/config/InferenceConfig.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModel.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModelDict.scala, src/test/scala/ai/nixiesearch/config/InferenceConfigTest.scala, src/test/scala/ai/nixiesearch/core/nn/model/embedding/OnnxBiEncoderTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/362
=> add support for composite ONNX models (like bge-m3)

build.sbt, src/main/scala/ai/nixiesearch/index/Indexer.scala, src/main/scala/ai/nixiesearch/main/Logo.scala, src/main/scala/ai/nixiesearch/util/GPUUtils.scala
Before that we used a set of heuristics based on classpath to guess it - now we can make it simpler and more reliable.
=> switch to buildinfo for guessing CUDA support

src/main/scala/ai/nixiesearch/core/Document.scala, src/test/scala/ai/nixiesearch/core/DocumentJsonTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/419
=> fix crash on json array parsing of undefined fields

src/main/scala/ai/nixiesearch/api/SearchRoute.scala, src/main/scala/ai/nixiesearch/core/nn/model/generative/GenerativeModel.scala, src/main/scala/ai/nixiesearch/core/nn/model/generative/GenerativeModelDict.scala, src/main/scala/ai/nixiesearch/index/Searcher.scala, src/test/scala/ai/nixiesearch/api/query/RAGTest.scala, src/test/scala/ai/nixiesearch/e2e/MSMarcoEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/RAGEndToEndTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/315
=> trim prompt right (and apply maxDocLength)

README.md, build_readme.py
fixes https://github.com/nixiesearch/nixiesearch/issues/456
=> get rid of chatgpt code to fix image URLs

.gitignore, docs/docs/features/inference/embeddings.md, docs/docs/features/inference/embeddings/sbert.md, docs/docs/index.md, docs/docs/reference/config.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/config/InferenceConfig.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModel.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModelDict.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedPooling.scala, src/test/python/embed_tests/build_embeds.py, src/test/python/embed_tests/inputs.csv, src/test/python/embed_tests/minilm.py, src/test/python/embed_tests/requirements.txt, src/test/resources/embeds/embeds.csv, src/test/scala/ai/nixiesearch/config/InferenceConfigTest.scala, src/test/scala/ai/nixiesearch/e2e/EmbeddingInferenceEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/EmbeddingPythonMatchTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/465
need to add test to validate it matches python impl
=> add support for cls pooling

docs/docs/features/inference/embeddings/models.csv, src/main/scala/ai/nixiesearch/config/InferenceConfig.scala, src/test/scala/ai/nixiesearch/core/nn/model/embedding/OnnxBiEncoderTest.scala, src/test/scala/ai/nixiesearch/e2e/EmbeddingInferenceEndToEndTest.scala
fixes https://github.com/nixiesearch/nixiesearch/issues/470
=> add support for bge-m3 model

build.sbt
=> migrate to ubuntu 24.04 for docker image

project/Deps.scala
=> bump llamacpp to b4902

.github/workflows/tests.yml, docs/docs/features/inference/embeddings.md, docs/docs/features/inference/embeddings/openai.md, docs/docs/reference/config.md, src/main/scala/ai/nixiesearch/api/InferenceRoute.scala, src/main/scala/ai/nixiesearch/config/InferenceConfig.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModel.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/EmbedModelDict.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/cache/EmbeddingCache.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/providers/OnnxEmbedModel.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/providers/OpenAIEmbedModel.scala, src/test/resources/config/compat.yml, src/test/resources/config/distributed.yml, src/test/resources/config/msmarco.yml, src/test/resources/config/suggest.yml, src/test/scala/ai/nixiesearch/config/ConfigTest.scala, src/test/scala/ai/nixiesearch/config/InferenceConfigTest.scala, src/test/scala/ai/nixiesearch/core/nn/model/embedding/OnnxBiEncoderTest.scala, src/test/scala/ai/nixiesearch/e2e/APIEmbedEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/EmbeddingInferenceEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/EmbeddingPythonMatchTest.scala, src/test/scala/ai/nixiesearch/util/Tags.scala, src/test/scala/ai/nixiesearch/util/TestInferenceConfig.scala
=> add OpenAI embedding support

docs/docs/features/inference/embeddings.md, docs/docs/features/inference/embeddings/cohere.md, docs/docs/reference/config.md, src/main/scala/ai/nixiesearch/config/InferenceConfig.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/providers/CohereEmbedModel.scala, src/test/scala/ai/nixiesearch/config/InferenceConfigTest.scala, src/test/scala/ai/nixiesearch/e2e/APIEmbedEndToEndTest.scala
=> Cohere embeddings support

.github/workflows/e2e-embed-api.yml
=> CI: add test for API based embedders

.github/workflows/e2e-connector.yml, .github/workflows/e2e-embed-api.yml, .github/workflows/e2e-embed.yml, .github/workflows/tests.yml
=> remove model cache from actions cache

docs/docs/api.md, docs/docs/help/usage_stats.md, docs/docs/openapi.yaml, docs/docs/reference/config.md, docs/mkdocs.yml, src/main/scala/ai/nixiesearch/api/AdminRoute.scala, src/main/scala/ai/nixiesearch/config/Config.scala, src/main/scala/ai/nixiesearch/config/CoreConfig.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/providers/OnnxEmbedModel.scala, src/main/scala/ai/nixiesearch/main/CliConfig.scala, src/main/scala/ai/nixiesearch/main/Main.scala, src/main/scala/ai/nixiesearch/main/subcommands/IndexMode.scala, src/main/scala/ai/nixiesearch/source/FileSource.scala, src/main/scala/ai/nixiesearch/source/KafkaSource.scala, src/main/scala/ai/nixiesearch/util/BooleanEnv.scala, src/main/scala/ai/nixiesearch/util/EnvVars.scala, src/main/scala/ai/nixiesearch/util/analytics/AnalyticsReporter.scala, src/main/scala/ai/nixiesearch/util/analytics/OnStartAnalyticsPayload.scala, src/main/scala/ai/nixiesearch/util/analytics/OnlinePayload.scala, src/test/scala/ai/nixiesearch/config/ConfigEnvSubstTest.scala, src/test/scala/ai/nixiesearch/e2e/MSMarcoEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/MoviesSuggestionEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/RAGEndToEndTest.scala, src/test/scala/ai/nixiesearch/e2e/RemoteIndexSearchEndToEndTest.scala, src/test/scala/ai/nixiesearch/index/compat/CompatUtil.scala, src/test/scala/ai/nixiesearch/main/CliConfigTest.scala, src/test/scala/ai/nixiesearch/main/subcommands/IndexModeTest.scala, src/test/scala/ai/nixiesearch/source/KafkaSourceTest.scala, src/test/scala/ai/nixiesearch/util/analytics/OnStartAnalyticsPayloadTest.scala
fixes #476 
We decided not to go with PostHog as it was too web-centric. We just dump data to a Google Sheet via webhook :)
=> Anonymous usage telemetry

docs/docs/help/support.md
=> doc: add support page

.github/workflows/e2e-embed-api.yml
Fix the CI break for e2e api test
=> CI: move secrets from top-level to job level def

src/main/scala/ai/nixiesearch/core/nn/model/embedding/providers/CohereEmbedModel.scala, src/main/scala/ai/nixiesearch/core/nn/model/embedding/providers/OpenAIEmbedModel.scala
As an extra check of users using wrong value for env var
=> add check to validate that openai/cohere keys are not empty

docs/mkdocs.yml
Doc was there, but we forgot to add it to TOC
=> doc: add cohere doc page to TOC

docs/docs/features/indexing/types/text.md, docs/docs/index.md, src/main/scala/ai/nixiesearch/config/mapping/SearchParams.scala, src/main/scala/ai/nixiesearch/core/codec/compat/Nixiesearch101Codec.scala, src/test/scala/ai/nixiesearch/api/query/SemanticQuantizationTest.scala
=> add support for BBQ/int1 quantization

docs/docs/features/indexing/format.md, docs/docs/features/indexing/types/text.md, src/main/scala/ai/nixiesearch/core/Document.scala, src/main/scala/ai/nixiesearch/core/field/TextField.scala, src/main/scala/ai/nixiesearch/util/DocumentEmbedder.scala, src/test/scala/ai/nixiesearch/core/DocumentJsonTest.scala
=> Support text pre-embedded JSON format on ingestion

docs/docs/openapi.yaml, src/main/scala/ai/nixiesearch/api/IndexModifyRoute.scala, src/main/scala/ai/nixiesearch/api/SearchRoute.scala, src/main/scala/ai/nixiesearch/index/Searcher.scala, src/test/scala/ai/nixiesearch/api/query/aggregation/json/AggregationEncoderJsonTest.scala, src/test/scala/ai/nixiesearch/api/query/json/SearchRequestTest.scala
As often the granularity of millis as integer is too low: it's just `1`, so what?
=> Make took field in all responses return seconds instead of millis

docs/docs/deployment/standalone.md, docs/docs/features/search/query/rank/ce.md
fixes https://github.com/nixiesearch/nixiesearch/issues/446
=> add docs on standalone mode

deploy/kubernetes/README.md, deploy/kubernetes/distributed/README.md, deploy/kubernetes/distributed/configmap.yaml, deploy/kubernetes/distributed/indexer-service.yaml, deploy/kubernetes/distributed/indexer-statefulset.yaml, deploy/kubernetes/distributed/searcher-deployment.yaml, deploy/kubernetes/distributed/searcher-service.yaml, deploy/kubernetes/standalone/README.md, deploy/kubernetes/standalone/configmap.yaml, deploy/kubernetes/standalone/deployment.yaml, deploy/kubernetes/standalone/pvc.yaml, deploy/kubernetes/standalone/service.yaml, deploy/nixiesearch.sh, docs/docs/deployment/distributed/kubernetes.md, docs/docs/deployment/distributed/overview.md
fixes https://github.com/nixiesearch/nixiesearch/issues/447
=> kubernetes deployment docs + manifests

project/Deps.scala, src/main/scala/ai/nixiesearch/util/S3Client.scala
Compile fix for https://github.com/nixiesearch/nixiesearch/pull/606
=> Update s3 to 2.31.78

build.sbt, src/main/scala/ai/nixiesearch/core/JsonDocumentStream.scala, src/main/scala/ai/nixiesearch/util/source/URLReader.scala, src/test/scala/ai/nixiesearch/core/JsonDocumentStreamTest.scala, src/test/scala/ai/nixiesearch/util/DatasetLoader.scala, src/test/scala/ai/nixiesearch/util/source/URLReaderTest.scala
Don't rely on extensions, guess format from file header
=> transparently decompress gzipped jsons
